# Generated by Django 6.0.7 on 2026-07-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paid_at',
            new_name='payment_date',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking'), ('Cash', 'Cash')], default='UPI', max_length=30),
        ),
    ]
