services:
  - type: web
    name: stayease
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python manage.py collectstatic --noinput && gunicorn stayease.wsgi --bind 0.0.0.0:10000