services:
  - type: web
    name: stayease
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput --no-input
      python manage.py migrate --noinput --verbosity 3
    startCommand: gunicorn stayease.wsgi --bind 0.0.0.0:10000