# Generated by Django 6.0.7 on 2026-07-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='available_rooms',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_type',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Resort', 'Resort'), ('Business', 'Business'), ('Budget', 'Budget')], default='luxury', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='parking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='restaurant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='total_rooms',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='wifi',
            field=models.BooleanField(default=True),
        ),
    ]
